name: Generate Log

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Log
      run: |
        echo "# Change Log" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        git log --pretty=format:"%ad" --date=short | sort -u | while read DATE; do
          echo "## $DATE" >> CHANGELOG.md
          git log --pretty=format:"- **%s**" --date=short --since="$DATE 00:00" --until="$DATE 23:59" --name-only | awk 'NF' | awk 'NR%2{printf "  - `%s`\n", $0; next}1' >> CHANGELOG.md
          echo "" >> CHANGELOG.md
        done

    - name: Commit Change Log
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "Update Change Log"
        git push
